GRANT SELECT, UPDATE, DELETE, INSERT ON TABLE bayes_token TO baruwa;
GRANT SELECT, UPDATE, DELETE, INSERT ON TABLE bayes_vars TO baruwa;
GRANT SELECT, DELETE, INSERT ON TABLE bayes_seen TO baruwa;
GRANT SELECT, DELETE, INSERT ON TABLE bayes_expire TO baruwa;
GRANT SELECT ON TABLE bayes_global_vars TO baruwa;
GRANT UPDATE, SELECT, INSERT ON bayes_vars_id_seq TO baruwa;
GRANT SELECT, UPDATE, DELETE, INSERT ON TABLE awl TO baruwa;